# Generated by Django 4.2.4 on 2023-08-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=30)),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('last_edit_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
