# Generated by Django 4.2.4 on 2023-08-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_content',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
